/*
Copyright 2023 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	v1beta1 "knative.dev/operator/pkg/apis/operator/v1beta1"
	scheme "knative.dev/operator/pkg/client/clientset/versioned/scheme"
)

// KnativeEventingsGetter has a method to return a KnativeEventingInterface.
// A group's client should implement this interface.
type KnativeEventingsGetter interface {
	KnativeEventings(namespace string) KnativeEventingInterface
}

// KnativeEventingInterface has methods to work with KnativeEventing resources.
type KnativeEventingInterface interface {
	Create(ctx context.Context, knativeEventing *v1beta1.KnativeEventing, opts v1.CreateOptions) (*v1beta1.KnativeEventing, error)
	Update(ctx context.Context, knativeEventing *v1beta1.KnativeEventing, opts v1.UpdateOptions) (*v1beta1.KnativeEventing, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, knativeEventing *v1beta1.KnativeEventing, opts v1.UpdateOptions) (*v1beta1.KnativeEventing, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.KnativeEventing, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.KnativeEventingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.KnativeEventing, err error)
	KnativeEventingExpansion
}

// knativeEventings implements KnativeEventingInterface
type knativeEventings struct {
	*gentype.ClientWithList[*v1beta1.KnativeEventing, *v1beta1.KnativeEventingList]
}

// newKnativeEventings returns a KnativeEventings
func newKnativeEventings(c *OperatorV1beta1Client, namespace string) *knativeEventings {
	return &knativeEventings{
		gentype.NewClientWithList[*v1beta1.KnativeEventing, *v1beta1.KnativeEventingList](
			"knativeeventings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.KnativeEventing { return &v1beta1.KnativeEventing{} },
			func() *v1beta1.KnativeEventingList { return &v1beta1.KnativeEventingList{} }),
	}
}
