# Copyright 2022 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knative-kafka-controller-post-install
  labels:
    app.kubernetes.io/version: "e6b002188068b4caebdba747eda522f465fa1583"
rules: []

---
# Copyright 2022 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-kafka-controller-post-install
  namespace: knative-eventing
  labels:
    app.kubernetes.io/version: "e6b002188068b4caebdba747eda522f465fa1583"

---
# Copyright 2020 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knative-kafka-storage-version-migrator
  labels:
    app.kubernetes.io/version: "e6b002188068b4caebdba747eda522f465fa1583"
rules:
  # Storage version upgrader needs to be able to patch CRDs.
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
      - "customresourcedefinitions/status"
    verbs:
      - "get"
      - "list"
      - "update"
      - "patch"
      - "watch"
  # Our own resources we care about.
  - apiGroups:
      - "sources.knative.dev"
    resources:
      - "kafkasources"
      - "kafkasources/finalizers"
      - "kafkasources/status"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "patch"
      - "watch"
  - apiGroups:
      - "messaging.knative.dev"
    resources:
      - "kafkachannels"
      - "kafkachannels/finalizers"
      - "kafkachannels/status"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "patch"
      - "watch"
  - apiGroups:
      - "eventing.knative.dev"
    resources:
      - "kafkasinks"
      - "kafkasinks/finalizers"
      - "kafkasinks/status"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "patch"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "get"
      - "list"

---
# Copyright 2020 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-kafka-storage-version-migrator
  namespace: knative-eventing
  labels:
    app.kubernetes.io/version: "e6b002188068b4caebdba747eda522f465fa1583"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-kafka-storage-version-migrator
  labels:
    app.kubernetes.io/version: "e6b002188068b4caebdba747eda522f465fa1583"
subjects:
  - kind: ServiceAccount
    name: knative-kafka-storage-version-migrator
    namespace: knative-eventing
roleRef:
  kind: ClusterRole
  name: knative-kafka-storage-version-migrator
  apiGroup: rbac.authorization.k8s.io

---
# Copyright 2022 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-kafka-controller-post-install
  labels:
    app.kubernetes.io/version: "e6b002188068b4caebdba747eda522f465fa1583"
subjects:
  - kind: ServiceAccount
    name: knative-kafka-controller-post-install
    namespace: knative-eventing
roleRef:
  kind: ClusterRole
  name: knative-kafka-controller-post-install
  apiGroup: rbac.authorization.k8s.io

---
# Copyright 2022 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-controller-post-install
  namespace: knative-eventing
  labels:
    app: kafka-controller-post-install
    app.kubernetes.io/version: "e6b002188068b4caebdba747eda522f465fa1583"
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: kafka-controller-post-install
        app.kubernetes.io/version: "e6b002188068b4caebdba747eda522f465fa1583"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: knative-kafka-controller-post-install
      restartPolicy: OnFailure
      containers:
        - name: post-install
          image: gcr.io/knative-releases/knative.dev/eventing-kafka-broker/control-plane/cmd/post-install@sha256:0ead3ffe891dfa0ffd8db4f11b902fac0cf437b3f0c264b425c42aa8c1bf82d4
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CHANNEL_GENERAL_CONFIG_MAP_NAME
              value: kafka-channel-config
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

---
# Copyright 2020 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: knative-kafka-storage-version-migrator
  namespace: knative-eventing
  labels:
    app: "knative-kafka-storage-version-migrator"
    app.kubernetes.io/version: "e6b002188068b4caebdba747eda522f465fa1583"
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: "knative-kafka-storage-version-migrator"
        app.kubernetes.io/version: "e6b002188068b4caebdba747eda522f465fa1583"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: knative-kafka-storage-version-migrator
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: gcr.io/knative-releases/knative.dev/pkg/apiextensions/storageversion/cmd/migrate@sha256:2d0247149f62a163a15555f5051d836cb20f10b0f776f1df4542e223514d7432
          env:
            - name: IGNORE_NOT_FOUND
              value: "true"
          args:
            - "kafkasources.sources.knative.dev"
            - "kafkachannels.messaging.knative.dev"
            - "kafkasinks.eventing.knative.dev"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

---
