knative_operator:
  knative_operator:
    image: gcr.io/knative-releases/knative.dev/operator/cmd/operator
    tag: v1.10.1
  operator_webhook:
    image: gcr.io/knative-releases/knative.dev/operator/cmd/webhook
    tag: v1.10.1
