run:
  timeout: 5m

  build-tags:
    - e2e
    - preupgrade
    - postupgrade
    - postdowngrade

issues:
  exclude-dirs:
    - pkg/client # Excludes generated client

linters:
  enable:
    - unconvert
    - prealloc
  disable:
    - errcheck
