apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: knative-eventing
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: imc-dispatcher-server-tls
  namespace: knative-eventing
spec:
  # Secret names are always required.
  secretName: imc-dispatcher-server-tls
  secretTemplate:
    labels:
      app.kubernetes.io/component: imc-dispatcher
      app.kubernetes.io/name: knative-eventing
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - imc-dispatcher.knative-eventing.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mt-broker-filter-server-tls
  namespace: knative-eventing
spec:
  # Secret names are always required.
  secretName: mt-broker-filter-server-tls
  secretTemplate:
    labels:
      app.kubernetes.io/component: broker-filter
      app.kubernetes.io/name: knative-eventing
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - broker-filter.knative-eventing.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mt-broker-ingress-server-tls
  namespace: knative-eventing
spec:
  # Secret names are always required.
  secretName: mt-broker-ingress-server-tls
  secretTemplate:
    labels:
      app.kubernetes.io/component: broker-ingress
      app.kubernetes.io/name: knative-eventing
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - broker-ingress.knative-eventing.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

---
