# Copyright 2020 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knative-eventing-post-install-job-role
  labels:
    eventing.knative.dev/release: "v1.0.2"
rules:
  # Storage version upgrader needs to be able to patch CRDs.
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
      - "customresourcedefinitions/status"
    verbs:
      - "get"
      - "list"
      - "update"
      - "patch"
      - "watch"
  # Our own resources we care about.
  - apiGroups:
      - "sources.knative.dev"
    resources:
      - "apiserversources"
      - "apiserversources/finalizers"
      - "apiserversources/status"
      - "containersources"
      - "containersources/finalizers"
      - "containersources/status"
      - "pingsources"
      - "pingsources/finalizers"
      - "pingsources/status"
      - "sinkbindings"
      - "sinkbindings/finalizers"
      - "sinkbindings/status"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "patch"
      - "watch"
  - apiGroups:
      - "eventing.knative.dev"
    resources:
      - "brokers"
      - "brokers/finalizers"
      - "brokers/status"
      - "eventtypes"
      - "eventtypes/finalizers"
      - "eventtypes/status"
      - "triggers"
      - "triggers/finalizers"
      - "triggers/status"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "patch"
      - "watch"
  - apiGroups:
      - "messaging.knative.dev"
    resources:
      - "channels"
      - "channels/finalizers"
      - "channels/status"
      - "inmemorychannels"
      - "inmemorychannels/finalizers"
      - "inmemorychannels/status"
      - "subscriptions"
      - "subscriptions/finalizers"
      - "subscriptions/status"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "patch"
      - "watch"
  - apiGroups:
      - "flows.knative.dev"
    resources:
      - "parallels"
      - "parallels/finalizers"
      - "parallels/status"
      - "sequences"
      - "sequences/finalizers"
      - "sequences/status"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "patch"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "get"
      - "list"

---
# Copyright 2020 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-eventing-post-install-job
  namespace: knative-eventing
  labels:
    eventing.knative.dev/release: "v1.0.2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-eventing-post-install-job-role-binding
  labels:
    eventing.knative.dev/release: "v1.0.2"
subjects:
  - kind: ServiceAccount
    name: knative-eventing-post-install-job
    namespace: knative-eventing
roleRef:
  kind: ClusterRole
  name: knative-eventing-post-install-job-role
  apiGroup: rbac.authorization.k8s.io

---
# Copyright 2020 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  generateName: storage-version-migration-eventing-
  namespace: knative-eventing
  labels:
    app: "storage-version-migration-eventing"
    eventing.knative.dev/release: "v1.0.2"
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: "storage-version-migration-eventing"
        eventing.knative.dev/release: "v1.0.2"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: knative-eventing-post-install-job
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: gcr.io/knative-releases/knative.dev/eventing/vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate@sha256:26b72d127fd93cf0f2f9ffec1ca350052cbec4858e8a7a68d24322f28a577477
          args:
            - "apiserversources.sources.knative.dev"
            - "brokers.eventing.knative.dev"
            - "channels.messaging.knative.dev"
            - "containersources.sources.knative.dev"
            - "eventtypes.eventing.knative.dev"
            - "inmemorychannels.messaging.knative.dev"
            - "parallels.flows.knative.dev"
            - "pingsources.sources.knative.dev"
            - "sequences.flows.knative.dev"
            - "sinkbindings.sources.knative.dev"
            - "subscriptions.messaging.knative.dev"
            - "triggers.eventing.knative.dev"

---
