#!/usr/bin/env bash

# Copyright 2025 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Syncs ClusterRole definitions from config/rbac/role.yaml to the Helm chart.
# Replaces app.kubernetes.io/version: devel with "{{ .Chart.Version }}" for Helm.
#
# Usage: hack/sync-helm-rbac.sh

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

ROLE_SRC="${REPO_ROOT_DIR}/config/rbac/role.yaml"
HELM_RBAC_DIR="${REPO_ROOT_DIR}/config/charts/knative-operator/templates/rbac"
BOILERPLATE_YAML="${REPO_ROOT_DIR}/hack/boilerplate/boilerplate.yaml.txt"

mkdir -p "${HELM_RBAC_DIR}"

if ! command -v yq >/dev/null 2>&1; then
  echo "yq is required but not found. Run ./hack/update-codegen.sh first." >&2
  exit 1
fi

echo "Syncing ClusterRoles from ${ROLE_SRC} to ${HELM_RBAC_DIR}"

write_clusterrole() {
  local name="$1"
  local target="$2"

  echo "  Processing ClusterRole ${name} -> rbac/$(basename "${target}")"

  local tmp
  tmp="$(mktemp)"
  if ! yq eval "(select(.metadata.name == \"${name}\")) | .metadata.labels.\"app.kubernetes.io/version\" = \"{{ .Chart.Version }}\"" "${ROLE_SRC}" > "${tmp}"; then
    echo "ERROR: yq failed to extract ClusterRole ${name}"
    rm -f "${tmp}"
    exit 1
  fi

  if ! grep -qE '^kind:[[:space:]]+ClusterRole' "${tmp}"; then
    echo "ERROR: no ClusterRole document found for ${name} in ${ROLE_SRC}"
    rm -f "${tmp}"
    exit 1
  fi

  # Strip yq's leading comments so every template gets the same Apache-2.0 header;
  # eventing's ClusterRole in role.yaml does not preserve them.
  {
    echo "# Code generated by hack/sync-helm-rbac.sh; DO NOT EDIT."
    cat "${BOILERPLATE_YAML}"
    awk '/^kind:/{p=1} p' "${tmp}"
  } > "${target}"
  rm -f "${tmp}"
}

write_clusterrole "knative-serving-operator" "${HELM_RBAC_DIR}/serving-operator-role.yaml"
write_clusterrole "knative-eventing-operator" "${HELM_RBAC_DIR}/eventing-operator-role.yaml"

echo "Done. RBAC synced to ${HELM_RBAC_DIR}"
