#!/usr/bin/env bash

# Copyright 2025 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Syncs CRD definitions from config/crd/bases/ to the Helm chart templates.
# This script transforms generated CRD bases into Helm-ready CRD templates by
# adding Helm template variables for labels and the conversion webhook namespace.
#
# Usage: hack/sync-helm-crds.sh

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

HELM_CRD_DIR="${REPO_ROOT_DIR}/config/charts/knative-operator/templates/crds"
CRD_BASES_DIR="${REPO_ROOT_DIR}/config/crd/bases"

mkdir -p "${HELM_CRD_DIR}"

if ! command -v yq >/dev/null 2>&1; then
  echo "yq is required but not found. Run ./hack/update-codegen.sh first." >&2
  exit 1
fi

echo "Syncing CRDs from ${CRD_BASES_DIR} to ${HELM_CRD_DIR}"

for crd_file in "${CRD_BASES_DIR}"/*.yaml; do
  filename=$(basename "${crd_file}")
  short_name="${filename#operator.knative.dev_}"
  target="${HELM_CRD_DIR}/${short_name}"

  echo "  Processing ${filename} -> crds/${short_name}"

  if [[ "$(yq eval '.spec.conversion.webhook.clientConfig.service.namespace // ""' "${crd_file}")" != "knative-operator" ]]; then
    echo "ERROR: ${filename} is missing the operator conversion webhook. Run ./hack/update-crd-conversion.sh first." >&2
    exit 1
  fi

  # -c keeps compact sequence indentation so "- name:" stays flush with its parent key.
  if ! yq eval -c '
    .metadata.labels."app.kubernetes.io/version" = "{{ .Chart.Version }}" |
    .metadata.labels."app.kubernetes.io/name" = "knative-operator" |
    .spec.conversion.webhook.clientConfig.service.namespace = "{{ .Release.Namespace }}"
  ' "${crd_file}" > "${target}"; then
    echo "ERROR: yq failed to process ${filename}"
    rm -f "${target}"
    exit 1
  fi

  tmp="${target}.tmp"
  echo "# Code generated by hack/sync-helm-crds.sh; DO NOT EDIT." > "${tmp}"
  cat "${target}" >> "${tmp}"
  mv "${tmp}" "${target}"
done

echo "Done. CRDs synced to ${HELM_CRD_DIR}"
